import { Appointment, MedicalRecord, Medication, Bill, Patient, Doctor } from "./types";

export const mockPatient: Patient = {
  id: "p1",
  name: "Sarah Johnson",
  email: "sarah.johnson@email.com",
  role: "patient",
  phone: "+1 555-0123",
  dateOfBirth: "1985-03-15",
  bloodGroup: "A+",
  allergies: ["Penicillin", "Peanuts"],
  chronicConditions: ["Hypertension"],
  familyMembers: [
    { id: "f1", name: "John Johnson", relationship: "Spouse", dateOfBirth: "1982-07-22" },
    { id: "f2", name: "Emma Johnson", relationship: "Daughter", dateOfBirth: "2012-11-08" },
  ],
};

export const mockDoctor: Doctor = {
  id: "d1",
  name: "Dr. Michael Chen",
  email: "dr.chen@medsense.com",
  role: "doctor",
  phone: "+1 555-0456",
  specialty: "Internal Medicine",
  registrationNumber: "MED-2024-1234",
  clinics: [
    { id: "c1", name: "Downtown Medical Center", address: "123 Health Ave, Suite 400", timings: "Mon-Fri 9AM-5PM" },
    { id: "c2", name: "Westside Clinic", address: "456 Care Blvd", timings: "Sat 10AM-2PM" },
  ],
};

export const mockAppointments: Appointment[] = [
  {
    id: "a1",
    patientId: "p1",
    patientName: "Sarah Johnson",
    doctorId: "d1",
    doctorName: "Dr. Michael Chen",
    date: "2024-12-20",
    time: "10:00 AM",
    mode: "in-person",
    status: "confirmed",
    reason: "Follow-up for blood pressure",
  },
  {
    id: "a2",
    patientId: "p1",
    patientName: "Sarah Johnson",
    doctorId: "d2",
    doctorName: "Dr. Emily Watson",
    date: "2024-12-22",
    time: "2:30 PM",
    mode: "video",
    status: "pending",
    reason: "Annual checkup",
  },
  {
    id: "a3",
    patientId: "p2",
    patientName: "Robert Miller",
    doctorId: "d1",
    doctorName: "Dr. Michael Chen",
    date: "2024-12-20",
    time: "11:30 AM",
    mode: "in-person",
    status: "confirmed",
    reason: "Diabetes management",
  },
  {
    id: "a4",
    patientId: "p3",
    patientName: "Lisa Anderson",
    doctorId: "d1",
    doctorName: "Dr. Michael Chen",
    date: "2024-12-20",
    time: "3:00 PM",
    mode: "phone",
    status: "confirmed",
    reason: "Lab results discussion",
  },
  {
    id: "a5",
    patientId: "p1",
    patientName: "Sarah Johnson",
    doctorId: "d1",
    doctorName: "Dr. Michael Chen",
    date: "2024-12-10",
    time: "9:00 AM",
    mode: "in-person",
    status: "completed",
    reason: "Initial consultation",
    notes: "Patient presented with elevated blood pressure. Prescribed Lisinopril 10mg daily.",
  },
];

export const mockRecords: MedicalRecord[] = [
  {
    id: "r1",
    patientId: "p1",
    type: "lab",
    title: "Complete Blood Count (CBC)",
    date: "2024-12-15",
    hospital: "City Medical Lab",
    doctor: "Dr. Michael Chen",
    summary: "All values within normal range. Hemoglobin: 14.2 g/dL, WBC: 7,500/mcL",
    aiSummary: "Your blood test results are normal. All key indicators including red blood cells, white blood cells, and platelets are within healthy ranges.",
    tags: ["routine", "blood-work"],
  },
  {
    id: "r2",
    patientId: "p1",
    type: "imaging",
    title: "Chest X-Ray",
    date: "2024-12-10",
    hospital: "Downtown Medical Center",
    doctor: "Dr. Emily Watson",
    summary: "No abnormalities detected. Lungs clear, heart size normal.",
    aiSummary: "Your chest X-ray shows healthy lungs with no signs of infection or abnormalities. Heart appears normal in size.",
    tags: ["routine", "imaging"],
  },
  {
    id: "r3",
    patientId: "p1",
    type: "prescription",
    title: "Blood Pressure Management",
    date: "2024-12-10",
    hospital: "Downtown Medical Center",
    doctor: "Dr. Michael Chen",
    summary: "Lisinopril 10mg - Once daily in the morning",
    aiSummary: "New prescription for blood pressure control. Take one tablet every morning. Monitor blood pressure weekly.",
    tags: ["hypertension", "chronic"],
  },
  {
    id: "r4",
    patientId: "p1",
    type: "lab",
    title: "Lipid Panel",
    date: "2024-11-28",
    hospital: "City Medical Lab",
    doctor: "Dr. Michael Chen",
    summary: "LDL slightly elevated at 145 mg/dL. HDL: 55 mg/dL. Total Cholesterol: 220 mg/dL",
    aiSummary: "Your cholesterol is slightly high. Consider dietary changes - reduce saturated fats and increase fiber intake. Follow-up recommended in 3 months.",
    tags: ["cholesterol", "attention-needed"],
  },
  {
    id: "r5",
    patientId: "p1",
    type: "visit-note",
    title: "Annual Physical Exam",
    date: "2024-10-15",
    hospital: "Downtown Medical Center",
    doctor: "Dr. Michael Chen",
    summary: "Overall health good. Blood pressure slightly elevated at 138/88. Weight stable. Recommended lifestyle modifications.",
    aiSummary: "Your annual checkup shows generally good health. Blood pressure needs attention - lifestyle changes recommended before considering medication.",
    tags: ["annual", "routine"],
  },
];

export const mockMedications: Medication[] = [
  {
    id: "m1",
    patientId: "p1",
    name: "Lisinopril",
    dosage: "10mg",
    frequency: "Once daily",
    timing: ["8:00 AM"],
    startDate: "2024-12-10",
    prescribedBy: "Dr. Michael Chen",
    isActive: true,
    adherence: 95,
    notes: "Take in the morning with or without food",
  },
  {
    id: "m2",
    patientId: "p1",
    name: "Vitamin D3",
    dosage: "2000 IU",
    frequency: "Once daily",
    timing: ["9:00 AM"],
    startDate: "2024-06-01",
    prescribedBy: "Dr. Emily Watson",
    isActive: true,
    adherence: 88,
    notes: "Take with breakfast for better absorption",
  },
  {
    id: "m3",
    patientId: "p1",
    name: "Metformin",
    dosage: "500mg",
    frequency: "Twice daily",
    timing: ["8:00 AM", "8:00 PM"],
    startDate: "2024-01-15",
    endDate: "2024-08-15",
    prescribedBy: "Dr. Michael Chen",
    isActive: false,
    adherence: 92,
    notes: "Discontinued - glucose levels normalized",
  },
];

export const mockBills: Bill[] = [
  {
    id: "b1",
    patientId: "p1",
    provider: "Downtown Medical Center",
    type: "consultation",
    amount: 150,
    date: "2024-12-10",
    status: "paid",
    description: "Initial consultation with Dr. Chen",
  },
  {
    id: "b2",
    patientId: "p1",
    provider: "City Medical Lab",
    type: "lab",
    amount: 280,
    date: "2024-12-15",
    status: "claim-pending",
    insuranceCovered: 224,
    description: "CBC and Lipid Panel tests",
  },
  {
    id: "b3",
    patientId: "p1",
    provider: "MedPlus Pharmacy",
    type: "pharmacy",
    amount: 45,
    date: "2024-12-10",
    status: "paid",
    description: "Lisinopril 10mg - 30 tablets",
  },
  {
    id: "b4",
    patientId: "p1",
    provider: "Downtown Medical Center",
    type: "hospital",
    amount: 350,
    date: "2024-12-10",
    status: "unpaid",
    insuranceCovered: 280,
    description: "Chest X-Ray imaging",
  },
];

export const mockDoctorPatients = [
  { ...mockPatient, lastVisit: "2024-12-10", nextAppointment: "2024-12-20" },
  {
    id: "p2",
    name: "Robert Miller",
    email: "robert.m@email.com",
    role: "patient" as const,
    phone: "+1 555-0789",
    dateOfBirth: "1972-08-30",
    bloodGroup: "O+",
    allergies: [],
    chronicConditions: ["Type 2 Diabetes", "Hypertension"],
    lastVisit: "2024-12-05",
    nextAppointment: "2024-12-20",
  },
  {
    id: "p3",
    name: "Lisa Anderson",
    email: "lisa.a@email.com",
    role: "patient" as const,
    phone: "+1 555-0321",
    dateOfBirth: "1990-12-05",
    bloodGroup: "B-",
    allergies: ["Sulfa drugs"],
    chronicConditions: [],
    lastVisit: "2024-11-28",
    nextAppointment: "2024-12-20",
  },
  {
    id: "p4",
    name: "James Wilson",
    email: "james.w@email.com",
    role: "patient" as const,
    phone: "+1 555-0654",
    dateOfBirth: "1965-04-18",
    bloodGroup: "AB+",
    allergies: ["Aspirin"],
    chronicConditions: ["Arthritis", "High Cholesterol"],
    lastVisit: "2024-12-12",
    nextAppointment: null,
  },
];
